### ISSUE TITLE
IMU data timestamp jump

### ISSUE THREAD

**Issue by JiaheXu** [cubicleguy/ess_imu_driver2#2]
Hi Epson developer,

I am using an Epson G370 IMU using UART-USB adaptor, the EXT2 pin is connected to a PPS source. When I check the time stamp, the sec part jumps back and forth for example it shows XXX522, XXX523, XXX523, XXX521, the sec part is not monotonic. How to solve this issue?

**Comment by cubicleguy** [comment]
Hello,

Can you confirm that you are using "tc_launch.py" to launch the driver?
i.e. ros2 launch ess_imu_driver2 **tc_launch.py**

This will set the time_correction_en parameter to "true".

You should be able to see id the parameter is set to true by reviewing the console output you launch the driver.

[ess_imu_driver2_node-1] [INFO] [1722455573.931168183] [epson_node]: frame_id:                  imu_link
**[ess_imu_driver2_node-1] [INFO] [1722455573.931458588] [epson_node]: time_correction_en:        1**
[ess_imu_driver2_node-1] [INFO] [1722455573.931508699] [epson_node]: burst_polling_rate:        4000.0

**Comment by cubicleguy** [comment]
Hello,
Thanks for your patience, I found the bug in TimeCorrection::get_stamp().
The implemented bug-fix which will be updated to this repo within 1 week.
